name: Add Submodule

on:
  workflow_dispatch:
    inputs:
        to-add:
            description: 'What submodule do you want to add?'
            required: true
            type: string

permissions:
  contents: write

concurrency:
  group: add-modules-${{ github.ref }}
  cancel-in-progress: false

jobs:
  add-modules:
    name: Add ${{ inputs.to-add }} Submodule
    runs-on: ubuntu-latest

    # https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Git Submodule Update
      run: |
        git submodule add https://github.com/${{ inputs.to-add }}

    - name: Commit update
      run: |
        git config --global user.name 'Submodule Adder'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Add ${{ inputs.to-add }} submodule" && git push || echo "No changes to commit"