name: Check for Updates

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

concurrency:
  group: update-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-for-updates:
    strategy:
        fail-fast: false
        matrix:
          config:
          - name: Hours
            repo: skiovox-extensions/clock-hours
            
          - name: Minutes
            repo: skiovox-extensions/clock-minutes
  
          - name: Seconds
            repo: skiovox-extensions/clock-seconds
  
          - name: AM & PM
            repo: skiovox-extensions/clock-ampm

          - name: Analog
            repo: skiovox-extensions/clock-analog

    name: Get Latest Release (${{ matrix.config.name }})
    runs-on: ubuntu-latest

    # https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout latest release of Lua
      run: |
        url="https://api.github.com/repos/${{ matrix.config.repo }}/releases/latest"
        assetsurl=$(curl -s "$url" | jq -r '.assets_url')
        =$(curl -s "$url" | jq -r '.assets_url')
        

    #- name: Commit Update
    #  run: |
    #    git config --global user.name 'Lua Submodule Updater'
    #    git config --global user.email 'bot@noreply.github.com'
    #    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    #    git commit -am "Update Lua" && git push || echo "No changes to commit"