name: Update Submodules

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

concurrency:
  group: update-modules-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-modules:
    name: Update Modules
    runs-on: ubuntu-latest

    # https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --init --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'Submodule Updater'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Update submodules" && git push || echo "No changes to commit"